# -*- coding: utf-8 -*-
"""playing_craps

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12ajK7d5TyhnzosXytzzMBm0QOF-c7ern
"""



#rolling 2 6 sided die 6,000,000 times 
"""Roll a six-sided die 6,000,000 times"""
import random
#Face fruequence counters
freq1 = 0
freq2 = 0
freq3 = 0
freq4 = 0
freq5 = 0
freq6 = 0
freq7 = 0
freq8 = 0
freq9 = 0
freq10 = 0 
freq11 = 0
freq12 = 0

trials = 6_000_000


#6,000,000 die rolls 

for roll in range(trials): 
  face = random.randrange(1, 7) + random.randrange(1, 7)

  #increment counter adds 1 to the appropriate counter variable
  if face == 1:  # we use nested control to determine the amount of times each die face appears. 
    freq1 += 1
  elif face == 2:
    freq2 += 1
  elif face == 3:
    freq3 += 1
  elif face == 4:
    freq4 += 1
  elif face == 5:
    freq5 += 1
  elif face == 6:
    freq6 += 1
  elif face == 7:
    freq7 += 1
  elif face == 8:
    freq8 += 1
  elif face == 9:
    freq9 += 1
  elif face == 10:
    freq10 += 1
  elif face == 11:
    freq11 += 1
  elif face == 12:
    freq12 += 1

print(f'Face{"Frequency":>13}') #this prints  the output 'Face' and 'Frequency' as headers, and spaces the output of the Face column to 4 spaces to the left, and 13 spaces for the 
print(f'{1:>4}{freq1:>13}')  # frequency column so that all numbers align. 
print(f'{2:>4}{freq2:>13}')
print(f'{3:>4}{freq3:>13}')
print(f'{4:>4}{freq4:>13}')
print(f'{5:>4}{freq5:>13}')
print(f'{6:>4}{freq6:>13}')
print(f'{7:>4}{freq7:>13}')
print(f'{8:>4}{freq8:>13}')
print(f'{9:>4}{freq9:>13}')
print(f'{10:>4}{freq10:>13}')
print(f'{11:>4}{freq11:>13}')
print(f'{12:>4}{freq12:>13}')

craps = freq2 + freq3 + freq12
win = freq7 + freq11
print('Craps:', craps/trials)
print('Win', win/trials)